-- AlterTable
ALTER TABLE "invoices" ADD COLUMN     "lastRetryAt" TIMESTAMP(3),
ADD COLUMN     "maxRetries" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "nextRetryAt" TIMESTAMP(3),
ADD COLUMN     "retryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "retryEnabled" BOOLEAN NOT NULL DEFAULT true;
